services:
  - type: web
    name: startup-connect-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://startup-connect-backend.onrender.com
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html" 